/***************************************************************************
 * The contents of this file were generated with Amplify Studio.           *
 * Please refrain from making any modifications to this file.              *
 * Any changes to this file will be overwritten when running amplify pull. *
 **************************************************************************/

/* eslint-disable */
import * as React from "react";
import { getOverrideProps } from "@aws-amplify/ui-react/internal";
import { Flex, Text, View } from "@aws-amplify/ui-react";
export default function AccountPageComp(props) {
  const { overrides, ...rest } = props;
  return (
    <View
      width="1440px"
      height="1024px"
      display="block"
      gap="unset"
      alignItems="unset"
      justifyContent="unset"
      overflow="hidden"
      position="relative"
      padding="0px 0px 0px 0px"
      backgroundColor="rgba(255,255,255,1)"
      {...rest}
      {...getOverrideProps(overrides, "AccountPageComp")}
    >
      <View {...getOverrideProps(overrides, "NavBar")}></View>
      <View
        width="1322px"
        height="840px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="130px"
        left="37px"
        boxShadow="0px 4px 4px rgba(0, 0, 0, 0.25)"
        padding="0px 0px 0px 0px"
        backgroundColor="rgba(255,255,255,1)"
        {...getOverrideProps(overrides, "Rectangle 3")}
      ></View>
      <Text
        fontFamily="Playfair Display"
        fontSize="24px"
        fontWeight="700"
        color="rgba(0,0,0,1)"
        lineHeight="31.99199867248535px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="unset"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="692px"
        left="638px"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="Make:"
        {...getOverrideProps(overrides, "Make:")}
      ></Text>
      <Text
        fontFamily="Playfair Display"
        fontSize="24px"
        fontWeight="700"
        color="rgba(0,0,0,1)"
        lineHeight="31.99199867248535px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="102px"
        height="40px"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="692px"
        left="863px"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="Model:"
        {...getOverrideProps(overrides, "Model:")}
      ></Text>
      <Text
        fontFamily="Playfair Display"
        fontSize="24px"
        fontWeight="700"
        color="rgba(0,0,0,1)"
        lineHeight="31.99199867248535px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="unset"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="692px"
        left="1085px"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="Color:"
        {...getOverrideProps(overrides, "Color:")}
      ></Text>
      <Text
        fontFamily="Playfair Display"
        fontSize="32px"
        fontWeight="700"
        color="rgba(0,0,0,1)"
        lineHeight="42.65599822998047px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="unset"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="605px"
        left="626px"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="Truck Information"
        {...getOverrideProps(overrides, "Truck Information")}
      ></Text>
      <Text
        fontFamily="Playfair Display"
        fontSize="32px"
        fontWeight="700"
        color="rgba(0,0,0,1)"
        lineHeight="42.65599822998047px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="unset"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="460px"
        left="626px"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="Email:"
        {...getOverrideProps(overrides, "Email:")}
      ></Text>
      <Text
        fontFamily="Playfair Display"
        fontSize="32px"
        fontWeight="700"
        color="rgba(0,0,0,1)"
        lineHeight="42.65599822998047px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="unset"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="149px"
        left="626px"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="First Name:"
        {...getOverrideProps(overrides, "First Name:")}
      ></Text>
      <Text
        fontFamily="Playfair Display"
        fontSize="32px"
        fontWeight="700"
        color="rgba(0,0,0,1)"
        lineHeight="42.65599822998047px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="unset"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="149px"
        left="992px"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="Last Name:"
        {...getOverrideProps(overrides, "Last Name:")}
      ></Text>
      <Flex
        gap="10px"
        direction="row"
        width="unset"
        height="unset"
        justifyContent="flex-start"
        alignItems="flex-start"
        position="absolute"
        top="242px"
        left="616px"
        padding="10px 10px 10px 10px"
        {...getOverrideProps(overrides, "Frame 1")}
      >
        <Text
          fontFamily="Playfair Display"
          fontSize="36px"
          fontWeight="700"
          color="rgba(0,0,0,1)"
          lineHeight="47.987998962402344px"
          textAlign="left"
          display="block"
          direction="column"
          justifyContent="unset"
          width="unset"
          height="unset"
          gap="unset"
          alignItems="unset"
          shrink="0"
          position="relative"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="Age:"
          {...getOverrideProps(overrides, "Age:")}
        ></Text>
      </Flex>
      <Text
        fontFamily="Playfair Display"
        fontSize="24px"
        fontWeight="700"
        color="rgba(0,0,0,1)"
        lineHeight="31.99199867248535px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="unset"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="322px"
        left="626px"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="Month:"
        {...getOverrideProps(overrides, "Month:")}
      ></Text>
      <Text
        fontFamily="Playfair Display"
        fontSize="24px"
        fontWeight="700"
        color="rgba(0,0,0,1)"
        lineHeight="31.99199867248535px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="unset"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="322px"
        left="892px"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="Day:"
        {...getOverrideProps(overrides, "Day:")}
      ></Text>
      <Text
        fontFamily="Playfair Display"
        fontSize="24px"
        fontWeight="700"
        color="rgba(0,0,0,1)"
        lineHeight="31.99199867248535px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="unset"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="323px"
        left="1045px"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="Year:"
        {...getOverrideProps(overrides, "Year:")}
      ></Text>
      <View
        width="116px"
        height="9px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="62px"
        left="1159px"
        boxShadow="0px 4px 4px rgba(0, 0, 0, 0.25)"
        padding="0px 0px 0px 0px"
        backgroundColor="rgba(0,0,0,1)"
        {...getOverrideProps(overrides, "Rectangle 2")}
      ></View>
      <Text
        fontFamily="Playfair Display"
        fontSize="36px"
        fontWeight="700"
        color="rgba(0,0,0,1)"
        lineHeight="47.987998962402344px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="unset"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="600px"
        left="101px"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="Payment Information"
        {...getOverrideProps(overrides, "Payment Information")}
      ></Text>
      <Text
        fontFamily="Playfair Display"
        fontSize="36px"
        fontWeight="700"
        color="rgba(0,0,0,1)"
        lineHeight="47.987998962402344px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="unset"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="339px"
        left="99px"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="Personal Information"
        {...getOverrideProps(overrides, "Personal Information")}
      ></Text>
      <Text
        fontFamily="Playfair Display"
        fontSize="36px"
        fontWeight="700"
        color="rgba(0,0,0,1)"
        lineHeight="47.987998962402344px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="unset"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="427px"
        left="174px"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="Login & Security"
        {...getOverrideProps(overrides, "Login & Security")}
      ></Text>
      <Text
        fontFamily="Playfair Display"
        fontSize="36px"
        fontWeight="700"
        color="rgba(0,0,0,1)"
        lineHeight="47.987998962402344px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="unset"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="692px"
        left="367px"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="FAQs"
        {...getOverrideProps(overrides, "FAQs")}
      ></Text>
      <Text
        fontFamily="Playfair Display"
        fontSize="36px"
        fontWeight="700"
        color="rgba(0,0,0,1)"
        lineHeight="47.987998962402344px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="unset"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="511px"
        left="300px"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="Sponsors"
        {...getOverrideProps(overrides, "Sponsors")}
      ></Text>
      <View
        width="182px"
        height="68px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="139px"
        left="802px"
        border="1px SOLID rgba(0,0,0,1)"
        boxShadow="0px 4px 4px rgba(0, 0, 0, 0.25)"
        padding="0px 0px 0px 0px"
        backgroundColor="rgba(217,217,217,1)"
        {...getOverrideProps(overrides, "FName")}
      ></View>
      <View
        width="145px"
        height="68px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="674px"
        left="711px"
        padding="0px 0px 0px 0px"
        backgroundColor="rgba(217,217,217,1)"
        {...getOverrideProps(overrides, "Make")}
      ></View>
      <View
        width="135px"
        height="68px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="674px"
        left="940px"
        padding="0px 0px 0px 0px"
        backgroundColor="rgba(217,217,217,1)"
        {...getOverrideProps(overrides, "Model")}
      ></View>
      <View
        width="135px"
        height="68px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="674px"
        left="1160px"
        padding="0px 0px 0px 0px"
        backgroundColor="rgba(217,217,217,1)"
        {...getOverrideProps(overrides, "Color")}
      ></View>
      <View
        width="548px"
        height="68px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="447px"
        left="732px"
        padding="0px 0px 0px 0px"
        backgroundColor="rgba(217,217,217,1)"
        {...getOverrideProps(overrides, "Email")}
      ></View>
      <View
        width="182px"
        height="68px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="139px"
        left="1159px"
        padding="0px 0px 0px 0px"
        backgroundColor="rgba(217,217,217,1)"
        {...getOverrideProps(overrides, "LName")}
      ></View>
      <View
        width="145px"
        height="49px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="315px"
        left="711px"
        padding="0px 0px 0px 0px"
        backgroundColor="rgba(217,217,217,1)"
        {...getOverrideProps(overrides, "Month")}
      ></View>
      <View
        width="91px"
        height="49px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="315px"
        left="947px"
        padding="0px 0px 0px 0px"
        backgroundColor="rgba(217,217,217,1)"
        {...getOverrideProps(overrides, "Day")}
      ></View>
      <View
        width="131px"
        height="49px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="315px"
        left="1105px"
        padding="0px 0px 0px 0px"
        backgroundColor="rgba(217,217,217,1)"
        {...getOverrideProps(overrides, "Year")}
      ></View>
      <View
        width="285px"
        height="77px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="813px"
        left="886px"
        padding="0px 0px 0px 0px"
        backgroundColor="rgba(217,217,217,1)"
        {...getOverrideProps(overrides, "Submit Button")}
      ></View>
    </View>
  );
}
